### ISSUE TITLE
iphone5s Already in DFU 

### ISSUE THREAD

**Issue by Nadroid** [MatthewPierson/Vieux#1]
error：

No device found in DFU mode, assuming device to be 32 Bit...
No valid 32 Bit information found. Exiting...

**Comment by MatthewPierson** [comment]
Are you sure it’s in DFU mode? Does iTunes detect it?

**Comment by Nadroid** [comment]
yes itunes can

python log:

Getting device model...
Version: 62acc7edad4dbffd94b7731539b892308c74699c - 14
Identified device as n53ap, iPhone6,2 in recovery mode...
INFO: device serial number is DX6PRS6NFR9M
ECID=78f889fa908
ApNonce=81e29eace486d0fb757659d3dcac0c874145308f
SepNonce=b27e7e7b4cb9bb6347909026e112b0a19592997b

ERROR: Couldn't get device model information

**Comment by Nadroid** [comment]
How can I get device model information?

**Comment by MatthewPierson** [comment]
Where is that Python log from? My tool doesn’t output that information, at least not all of it and not in that format?

**Comment by leicheng6563** [comment]
I have the same problem
A similar problem occurs when using "1033-OTA-Downgrader" (DFU is not recognized)
Use "igetnonce" tool print:
````
./igetnonce
Version: 62acc7edad4dbffd94b7731539b892308c74699c - 14
Identified device as n51ap, iPhone6,1 in recovery mode... 
INFO: device serial number is DNPPCEDPFNJJ
ECID=5b6a876d4f0
ApNonce=646e2752f901c2abbb955a835625188dc3d32890
SepNonce=79dd0241b7ff570763bef9ff53d09ef7c8022016
````

My macOS version is 10.13.6, iTunes recognizes device and prompts recovery.

**Comment by MatthewPierson** [comment]
Try using 10.14.x, High Sierra has some issues it looks like

**Comment by Nadroid** [comment]
My macOS version is 10.14.6, iTunes recognizes device and prompts recovery.

log is
`ERROR: Unsupported model...`

I printed it in the code 

print(str(supportedModels))

`output:iPhone6,1, iPhone6,2, iPhone8,4`

```
./igetnonce

Version: 62acc7edad4dbffd94b7731539b892308c74699c - 14
Identified device as n53ap, iPhone6,2 in recovery mode...
INFO: device serial number is DX6PRS6NFR9M
ECID=78f889fa908
ApNonce=7abe28e179be0eb0275bf2222e83b88fa5b5e7af
SepNonce=a421a5dcc3fb6d5c871804318ee67770c6b5db26
```
