### ISSUE TITLE
ipad mini2 A1491 ERROR: Unsupported model

### ISSUE THREAD

**Issue by hiqinoon** [MatthewPierson/Vieux#110]
hi master:

**Computer (please complete the following information):**
REQUIRED -
 - Macbook Pro 2017
 - MacOS Version : 10.14.6
 - Python Version : Python3.7
 - Vieux Version : 1.0.1

**iOS Device (please complete the following information):**
REQUIRED -
 - Device: iPad mini2 A1491
 - Desired Version:  iOS 10.3.3

**Additional context**
Screen Log:
[ Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
iPad_64bit_10.3.3_14G60_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
ERROR: Unsupported model...
Exiting... ]

**Comment by MatthewPierson** [comment]
Sorry, the Chinese iPad Mini 2 model (iPad4,6/A1491) is not supported, as it didn't ship with 7.0 like the other iPad Mini 2's, which is a requirement for this to work.
