### ISSUE TITLE
iPhone 4s to 6.1.3: Saving SHSH failed.

### ISSUE THREAD

**Issue by isudakov** [MatthewPierson/Vieux#128]
Hi! 
I am experiencing strange problem with downgrade my iPhone 4S from 9.3.6 to 6.1.3
Could anybody help me with it?

Computer Model: MacBook Pro (Retina, Mid 2012)
MacOS Version: 10.15.4 (19E287)
Python Version: Python 3.8.2
Vieux Version: "f2dc4f7c94432de13b63905dd54c48c2d3537db9"

Device: iPhone4,1
Desired Version: iOS 6.1.3

> Vieux - A tool for 32/64 Bit OTA downgrades
> 
> Current version is: 1.0.1
> If you are using a 64 Bit device then connect it in DFU Mode
> If you are using a 32 Bit device then just have it connected in NORMAL mode
> Files cleaned.
> iPhone4,1_6.1.3_10B329_Restore.ipsw is a zip archive!
> Starting IPSW unzipping
> Continuing...
> IPSW found at given path...
> Cleaning up old files...
> Files cleaned.
> Unzipping..
> Starting iBSS/iBEC patching
> Looks like you are downgrading an iPhone 4s to 6.1.3!
> Please enter your devices IP address (Find it in WiFi settings):
> 192.168.1.98
> Please enter the root password to your device (Default is 'alpine'):
> 
> Connecting to device via SSH...
> /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/client.py:835: UserWarning: Unknown ssh-rsa host key for 192.168.1.98: b'afe58dab768a257987098dd65385d291'
>   warnings.warn(
> Device is not running iOS 10.x, using normal TFP0 kloader...
> Please press the home button on your device or unplug and replug it back in.
> Waiting 10 seconds for you to do this.
> Getting SHSH...
> Saving SHSH failed.
> Please try again and report the error + full logs if it persists.
> Exiting...

**Comment by FrolovNikita** [comment]
@isudakov Hey! I had the same problem. This comment helped me today to downgrade my iPad mini 2 4,4 iOS 12.4.4 to 10.3.3. [Link: "Seems that is a problem with code signing executable."](https://github.com/MatthewPierson/Vieux/issues/126#issuecomment-612641213)

**Comment by isudakov** [comment]
Thanks a lot! It solved this problem for my iPad 4 and my iPhone 4S, but I have to notice a few things: I couldn't sign "futurerestore".

At first, got the following error:

> sudo codesign --sign - --force --deep futurerestore 
> /Library/Developer/CommandLineTools/usr/bin/codesign_allocate: file not in an order that can be processed (link edit information does not fill the __LINKEDIT segment): /Users/{aaa}/Vieux/resources/bin/futurerestore
> futurerestore: the codesign_allocate helper tool cannot be found or used

Then I tried:

> sudo xcode-select --reset
> sudo codesign --sign - --force --deep futurerestore 
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /Users/{aaaa}/Vieux/resources/bin/futurerestore malformed object (unknown load command 9)
> futurerestore: the codesign_allocate helper tool cannot be found or used

I decided to leave it as it is and try to downgrade my iPad and it was successfully done!
Then I tried to downgrade my iPhone 4S, but as I understood, the vieux tool couldn't switch my iphone do DFU mode during downgrade.
I catch this string:

> Device is not running iOS 10.x, using normal TFP0 kloader...

So I have restored "kloader" to the original state 

> git checkout -- resources/bin/kloader

and it solved my problem :)
