### ISSUE TITLE
iPad 4. Saving SHSH failed.

### ISSUE THREAD

**Issue by TrofimovAleksey** [MatthewPierson/Vieux#130]
**Describe the issue**
Saving SHSH failed. I have already tried all usb on my mac. Did pip3 install libusb and pip3 install libusb1.

**Screenshots**
Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
/Users/alex/Downloads/Vieux-master/iPad3,4_8.4.1_12H321_Restore (1).ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Starting iBSS/iBEC patching
Looks like you are downgrading an iPad4 to 8.4.1!
Please enter your devices IP address (Find it in WiFi settings):
192.168.1.5
Please enter the root password to your device (Default is 'alpine'):

Connecting to device via SSH...
/Library/Python/3.7/site-packages/paramiko/client.py:837: UserWarning: Unknown ssh-rsa host key for 192.168.1.5: b'a1fbd986bcf631383f74910d43b03fd5'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
Device is running iOS 10.x, using HGSP4 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
Saving SHSH failed.
Please try again and report the error + full logs if it persists.
Exiting...

**OR**

Connecting to device via SSH...
/Library/Python/3.7/site-packages/paramiko/client.py:837: UserWarning: Unknown ssh-rsa host key for 192.168.1.5: b'a1fbd986bcf631383f74910d43b03fd5'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
Device is running iOS 10.x, using HGSP4 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
ERROR: No Apple device in DFU Mode 0x1227 detected after 30.00 second timeout. Exiting.
Place the device into DFU mode again and re-run Vieux

**Computer (please complete the following information):**
 - Computer Model: iMac (27-inch, Late 2012)
 - MacOS Version: 10.15.4
 - Python Version: Python3.7
 - Vieux Version: 1.0.1

**iOS Device (please complete the following information):**
 - Device: iPad 3,4 (Wi-Fi) [MD513KS/A]
 - Desired Version: iOS 10.3.3 (14G60)

**Additional context**
Please help me! I'm already tired!

**Comment by isudakov** [comment]
Hm... We seem to have the same issue #128

**Comment by TrofimovAleksey** [comment]
Yep

**Comment by FrolovNikita** [comment]
@TrofimovAleksey @isudakov Hey! I had the same problem. This comment helped me today to downgrade my iPad mini 2 4,4 iOS 12.4.4 to 10.3.3. [Link: "Seems that is a problem with code signing executable."](https://github.com/MatthewPierson/Vieux/issues/126#issuecomment-612641213)

**Comment by TrofimovAleksey** [comment]
> @TrofimovAleksey @isudakov Hey! I had the same problem. This comment helped me today to downgrade my iPad mini 2 4,4 iOS 12.4.4 to 10.3.3. [Link: "Seems that is a problem with code signing executable."](https://github.com/MatthewPierson/Vieux/issues/126#issuecomment-612641213)

Thanks! This is a really working solution! Now my iPad has ios 8.4.1!!!

**Comment by TrofimovAleksey** [comment]
> Hm... We seem to have the same issue #128

Hi! This comment helped me today to downgrade my iPad: https://github.com/MatthewPierson/Vieux/issues/130#issuecomment-613541999
