### ISSUE TITLE
iPhone6,2 error Unsupported model

### ISSUE THREAD

**Issue by salvatore8686** [MatthewPierson/Vieux#142]
Can someone tell me why I'm getting this mistake?
macOS Mojave 10.14.6. iPhone in modality DFU Where am I wrong?

Vieux - A tool for 32/64 Bit OTA downgrades Current version is: 1.0.1 If you are using a 64 Bit device then connect it in DFU Mode If you are using a 32 Bit device then just have it connected in NORMAL mode Files cleaned. /Users/salvatoredebari/Desktop/Vieux-master/iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw is a zip archive! Starting IPSW unzipping Continuing... IPSW found at given path... Cleaning up old files... Files cleaned. Unzipping.. ERROR: Unsupported model... Exiting... MacBook-Pro:Vieux-master salvatoredebari$

**Comment by muhrizki1996** [comment]
same here.. iPhone 6,2 showing Unsupported model

![Screen Shot 2020-04-27 at 10 06 38](https://user-images.githubusercontent.com/46028018/80327480-cae4e500-886e-11ea-802e-e6d996ec5f07.png)

**Comment by johnwiichang** [comment]
If you are a macOS Catalina user, execute ./CatalinaFix.sh in the directory before executing vieux.

**Comment by muhrizki1996** [comment]
> If you are a macOS Catalina user, execute ./CatalinaFix.sh in the directory before executing vieux.

already do that

**Comment by salvatore8686** [comment]
> If you are a macOS Catalina user, execute ./CatalinaFix.sh in the directory before executing vieux.

I don't think the problem is due to the operating system, Until a few weeks ago, it worked well with the same operating system ( Mojave )

**Comment by salvatore8686** [comment]
I solved the problem, thanks anyway
![photo_2020-04-27_18-31-12](https://user-images.githubusercontent.com/16167507/80396730-5e410900-88b5-11ea-80c6-b13e309c663e.jpg)

**Comment by muhrizki1996** [comment]
> I solved the problem, thanks anyway
> ![photo_2020-04-27_18-31-12](https://user-images.githubusercontent.com/16167507/80396730-5e410900-88b5-11ea-80c6-b13e309c663e.jpg)

How you solve that problem pls?

**Comment by Daniel-Ramos** [comment]
Hi,
I'm having the same issue. I've already run ./CatalinaFix.sh, but still get 
ERROR: Unsupported model...

I have an iPhone 5s GM (6,1), trying to downgrade to 10.3.3 with this ipsw: https://ipsw.me/download/iPhone6,1/14G60

**Comment by Daniel-Ramos** [comment]
@salvatore8686

**Comment by Njerschow** [comment]
@salvatore8686 yo!

**Comment by m-zheng** [comment]
> Hi,
> I'm having the same issue. I've already run ./CatalinaFix.sh, but still get
> ERROR: Unsupported model...
> 
> I have an iPhone 5s GSM (6,1), trying to downgrade to 10.3.3 with this ipsw: https://ipsw.me/download/iPhone6,1/14G60

I had the same issue. Below is my solution.
1. go through each step in fix 2 (https://github.com/MatthewPierson/Vieux)
2. go through each step in fix 1 (https://github.com/MatthewPierson/Vieux)
3. try that again to see if the issue is fixed or not.
4. if 'ERROR: Unsupported model' is fixed but it throws another error msg saying 'usb.core.NoBackendError: No backend available', use command below to fix 
'brew install libusb'
5. now try again, if the issue still exists, use 'sudo' to run the command
6. make sure your phone is connected via default usb port, not ports in the external usb-hub.

**Comment by Mastermark2015** [comment]
YES ./CatalinaFix.sh cured my problem BUT im on Mojave LOL anyway all good.
What can i do now after the bypass ?? this is what i dont get as itunes , signal nothing works for what i have seen
