### ISSUE TITLE
No Apple device

### ISSUE THREAD

**Issue by czqn8** [MatthewPierson/Vieux#146]
Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
/Users/alan/Vieux/iPhone4,1_6.1.3_10B329_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Starting iBSS/iBEC patching
Looks like you are downgrading an iPhone 4s to 6.1.3!
Please enter your devices IP address (Find it in WiFi settings):
xx.xxxx.102
Please enter the root password to your device (Default is 'alpine'):

Connecting to device via SSH...
Device is not running iOS 10.x, using normal TFP0 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.

Getting SHSH...
ERROR: No Apple device in DFU Mode 0x1227 detected after 30.00 second timeout. Exiting.
Place the device into DFU mode again and re-run Vieux

**Comment by MatthewPierson** [comment]
Did you press the home button and/or reconnect the device when it says to? That usually causes this error

**Comment by czqn8** [comment]
No，still getting the same error

**Comment by Doofitator** [comment]
Bump. Exactly the same issues here.

    % ./vieux -i ~/Downloads/OTA_iPad3.1_8.4.1.ipsw

    Vieux - A tool for 32/64 Bit OTA downgrades

    Current version is: 1.0.1
    If you are using a 64 Bit device then connect it in DFU Mode
    If you are using a 32 Bit device then just have it connected in NORMAL mode
    Files cleaned.
    /Volumes/Home/homes/ashley/Downloads/OTA_iPad3.1_8.4.1.ipsw is a zip archive!
    Starting IPSW unzipping
    Continuing...
    IPSW found at given path...
    Cleaning up old files...
    Files cleaned.
    Unzipping..
    ERROR: Unable to discover device mode. Please make sure a device is attached.
    Starting iBSS/iBEC patching
    Looks like you are downgrading an iPad3 to 8.4.1!
    Please enter your devices IP address (Find it in WiFi settings):
    192.168.0.54
    Please enter the root password to your device (Default is 'alpine'):

    Connecting to device via SSH...
    Device is not running iOS 10.x, using normal TFP0 kloader...
    Please press the home button on your device or unplug and replug it back in.
    Waiting 10 seconds for you to do this.
    Getting SHSH...
    ERROR: No Apple device in DFU Mode 0x1227 detected after 30.00 second timeout. Exiting.
    Place the device into DFU mode again and re-run Vieux
