### ISSUE TITLE
Update/downgrade to iOS 11.4.1 iPad mini 2 (iPad 4,4) 

### ISSUE THREAD

**Issue by FrolovNikita** [MatthewPierson/Vieux#147]
Hello, @MatthewPierson!

My question is: Is it possible to update or downgrade an iPad mini 2 (iPad 4,4) to iOS 11.4.1 with help of Vieux?

Thank you in advance!

**Comment by MatthewPierson** [comment]
No sorry, as stated in the README, 64-Bit A7 devices can only be downgraded to 10.3.3 and no other firmware. You can tether downgrade to 11.4.1 using [SuccesionDown](https://github.com/MatthewPierson/SuccessionDown) to downgrade and [PyBoot](https://github.com/MatthewPierson/PyBoot) to boot though. You could also look into dualbooting 11.4.1 instead
