### ISSUE TITLE
iPhone4,1 error restore

### ISSUE THREAD

**Issue by salvatore8686** [MatthewPierson/Vieux#15]
MacBook-Pro:Vieux-master salvatoredebari$ ./vieux -i /Users/salvatoredebari/Desktop/Vieux-master/iPhone4\,1_6.1.3_10B329_Restore.ipsw 
Given IPSW Path is /Users/salvatoredebari/Desktop/Vieux-master/iPhone4,1_6.1.3_10B329_Restore.ipsw
Vieux - A tool for 32/64 Bit OTA downgrades
Still in BETA so expect issues/broken things
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in normal mode
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Unable to get SEPNonce from lockdownd
NOTE: Unable to get SepNonce from device
No device found in DFU mode, assuming device to be 32 Bit...
Starting iBSS/iBEC patching
Looks like you are downgrading an iPhone 4s to 6.1.3!
Please enter your devices IP address (Find it in WiFi settings):
192.168.1.204
Please enter the root password to your device (Default is 'alpine'):

Connecting to device via SSH...
/usr/local/lib/python3.7/site-packages/paramiko/client.py:837: UserWarning: Unknown ssh-rsa host key for 192.168.1.204: b'117247a089240b0ab775e0aec5c6251e'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
Device is not running iOS 10.x, using normal TFP0 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
Restoring...
Note that errors about 'BbSkeyId', 'FDR Client' and 'BasebandFirmware Node' are not important, just ignore them and only report errors that actually stop the restore.
ERROR: Unable to connect to FDR client (-2)
ERROR: Failed to start FDR Ctrl channel
ERROR: Unable to successfully restore device
Resoting Failed.
Please try again and report the error + full logs if it persists.
Exiting...
MacBook-Pro:Vieux-master salvatoredebari$

**Comment by MatthewPierson** [comment]
Download the latest version and try again. It will give you more output if it errors plus it also fixes some issues

**Comment by MatthewPierson** [comment]
^ Have posted more updates since then which should either fix the issue or allow me to see what's going wrong even easier

**Comment by salvatore8686** [comment]
Same problem.


MacBook-Pro:Vieux-master salvatoredebari$ ./vieux -i /Users/salvatoredebari/Desktop/Vieux-master/iPhone4\,1_6.1.3_10B329_Restore.ipsw 
Given IPSW Path is /Users/salvatoredebari/Desktop/Vieux-master/iPhone4,1_6.1.3_10B329_Restore.ipsw
Vieux - A tool for 32/64 Bit OTA downgrades
Still in BETA so expect issues/broken things
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in normal mode
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Unable to get SEPNonce from lockdownd
NOTE: Unable to get SepNonce from device
Starting iBSS/iBEC patching
Looks like you are downgrading an iPhone 4s to 6.1.3!
Please enter your devices IP address (Find it in WiFi settings):
192.168.1.204
Please enter the root password to your device (Default is 'alpine'):

Connecting to device via SSH...
/usr/local/lib/python3.7/site-packages/paramiko/client.py:837: UserWarning: Unknown ssh-rsa host key for 192.168.1.204: b'7090d7761bff046ce8ba35e998e301c3'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
Device is not running iOS 10.x, using normal TFP0 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
Restoring...
Note that errors about 'BbSkeyId', 'FDR Client' and 'BasebandFirmware Node' are not important, just ignore them and only report errors that actually stop the restore.
ERROR: Unable to connect to FDR client (-2)
ERROR: Failed to start FDR Ctrl channel
ERROR: Unable to successfully restore device
Resoting Failed.
Please try again and report the error + full logs if it persists.
Exiting...
MacBook-Pro:Vieux-master salvatoredebari$
