### ISSUE TITLE
iPad Mini 3 Not Supported?

### ISSUE THREAD

**Issue by ShikanoYuta** [MatthewPierson/Vieux#150]
As an A7 device , iPad Mini 3 hasn't been ever mentioned in anyone's article

**Comment by MatthewPierson** [comment]
The Mini 3 came with iOS 8, it never ran 7.0.x which means it doesn't have the OTA for 10.3.3 signed, which prevents it from downgrading sorry. Nothing that can be done about it

**Comment by ShikanoYuta** [comment]
I'm sorry 'bout that
