### ISSUE TITLE
usb.core.NoBackendError: No backend available

### ISSUE THREAD

**Issue by handsome-fstar** [MatthewPierson/Vieux#153]
**Describe the issue**
I connected my IPad Mini2 to DFU mode, then I typed sudo ./vieux -i ./iPad_64bit_10.3.3_14G60_Restore.ipsw

**Screenshots**
Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
./iPad_64bit_10.3.3_14G60_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Traceback (most recent call last):
  File "./vieux", line 89, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/fstar/Downloads/Vieux-master/ipsw.py", line 153, in unzipIPSW
    pwndfumode()
  File "/Users/fstar/Downloads/Vieux-master/restore.py", line 22, in pwndfumode
    device = dfu.acquire_device()
  File "/Users/fstar/Downloads/Vieux-master/resources/ipwndfu/dfu.py", line 20, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Computer (please complete the following information):**
REQUIRED -
 - Computer Model [macbook pro]  
 - MacOS Version [10.15.2]
 - Python Version [Python3.7.7]
 - Vieux Version [1.0.1]

**iOS Device (please complete the following information):**
REQUIRED -
 - Device: [iPad mini2, iPad4,4(A1489)]
 - Desired Version: [iOS 12.4.6]

**Comment by MatthewPierson** [comment]
Install brew if you haven't already then run "brew install libusb"

**Comment by handsome-fstar** [comment]
Thank you so much.
I downgrade my iPad mini2 successfully~~
