### ISSUE TITLE
Too many error (read description... ) 

### ISSUE THREAD

**Issue by Lazouk02** [MatthewPierson/Vieux#179]
Too many error with vieux, you should delete it from the web, He's useless...

**there are no screenshot because all the photos with all the errors that I should have done would have saturated my 256 GB of my iPhone X**

 - Computer Model MBP 2012  
 - MacOS Version : ALL ON THIS FUCKING EARTH! 
 - Python Version : 3.8

 - Device: iPhone 6,2
 - Desired Version: 10.3.3

**Additional context**

Come on, one more time! Big shit this method is shit shit shit ...
error after error and no one is fucked up to help anyone. I've been trying nonstop for 1 week on an iPhone 5s and a 2012 MBP I tried on Mojave, Catalina and even High Sierra ...
Nothing to do!
I got an error 248
Another blow I have an error 245 (-11) which turns out to be recurrent.
Then today I have a unsuported model whether on Mojave or Catalina with an official apple cable so the problem does not come from there ... and an iPhone in DFU mode also of course
it is an iPhone 5s (6.2) so I took care to take the corresponding IPSW but even. So fuck, I give up goodbye I'm crazy my 5s in the trash thank you shit method
(ps: I'm not a rage, just an enlightenment that speaks the truth)
bye developer chips that serve no purpose

**Comment by MatthewPierson** [comment]
Closing issue due to lack of manners and intelligence. If you are only looking for a place to get mad, go find somewhere else, this is a place for people who want help and are willing to be polite.
