### ISSUE TITLE
ERROR: Unsupported model...

### ISSUE THREAD

**Issue by Ay4y0** [MatthewPierson/Vieux#21]
OS X 10.11
iPad 4,2
ERROR: Unsupported model...

**Comment by MatthewPierson** [comment]
I can’t help you on 10.11.x. That os is well out of date now, please use Mojave or higher if possible.

**Comment by Ay4y0** [comment]
Ok 
Thank you i understood

**Comment by hais1992** [comment]
> I can’t help you on 10.11.x. That os is well out of date now, please use Mojave or higher if possible.

 Mojave 11.4.2 
iphone5S 
ERROR: Unsupported model...

**Comment by MatthewPierson** [comment]
@hais1992 I need the full logs, just telling me that is useless.

**Comment by hais1992** [comment]
> @hais1992 I need the full logs, just telling me that is useless.

![微信图片_20191218221520.jpg](https://i.loli.net/2019/12/18/Ay3U79YpMIKvEQ2.jpg)

**Comment by MatthewPierson** [comment]
On your device, are you sure it’s in dfu mode and not recovery mode?

**Comment by hais1992** [comment]
> On your device, are you sure it’s in dfu mode and not recovery mode?

yes, 

![微信图片_20191218221520.jpg](https://bkimg.cdn.bcebos.com/pic/f9dcd100baa1cd11640feb7bba12c8fcc3ce2d2b@wm_1,g_7,k_d2F0ZXIvYmFpa2UxMTY=,xp_5,yp_5)

**Comment by MatthewPierson** [comment]
If it has the iTunes logo on the screen it’s in recovery mode. Google how to enter dfu mode you can tell it’s in dfu mode when the screen is black but still detected by the computer.

**Comment by hais1992** [comment]
> If it has the iTunes logo on the screen it’s in recovery mode. Google how to enter dfu mode you can tell it’s in dfu mode when the screen is black but still detected by the computer.

Version of old point  old
![1.jpg](https://i.loli.net/2019/12/19/VQ41SlCKhLGZbP3.jpg)

Development version
![2.jpg](https://i.loli.net/2019/12/19/JOU4R9C3zf8dKqM.jpg)

**Comment by hais1992** [comment]
> If it has the iTunes logo on the screen it’s in recovery mode. Google how to enter dfu mode you can tell it’s in dfu mode when the screen is black but still detected by the computer.

Version of old point  old
![1.jpg](https://i.loli.net/2019/12/19/VQ41SlCKhLGZbP3.jpg)

Development version
![2.jpg](https://i.loli.net/2019/12/19/JOU4R9C3zf8dKqM.jpg)

**Comment by hais1992** [comment]
> If it has the iTunes logo on the screen it’s in recovery mode. Google how to enter dfu mode you can tell it’s in dfu mode when the screen is black but still detected by the computer.

New version
![3.jpg](https://i.loli.net/2019/12/19/tvqrQKkCIBdYfEM.jpg)

**Comment by MatthewPierson** [comment]
I will be closing this issue in 24 hours if you no longer need help/the issue has been resolved. If you still need help then comment with what you need and I will not close it.

**Comment by bkchucnc** [comment]
I get the same error "Unsupported mode...l".
![Snip20200412_1](https://user-images.githubusercontent.com/27678507/79071860-1d1ef580-7d08-11ea-88a8-ab70e79e3e86.png)
 Last month i did for some 5s were ok but now macbook can not recognize DFU mode (show in picture). How can i fix it?

**Comment by Charliefr3sh** [comment]
iphone 5s unsupported model

**Comment by Vladuka14** [comment]
OS X 10.15.6 (Catalina)
iPad 4,4 (Mini 2) in DFU (no iTunes logo).
ERROR: Unsupported model...

**Comment by lingtion** [comment]
OS X 11.6 , iphone5s in dfu mode, please help me.

=======
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
ERROR: Unsupported model...
