### ISSUE TITLE
Sending iBSS/iBEC Failed

### ISSUE THREAD

**Issue by igoriokas** [MatthewPierson/Vieux#226]
**Describe the issue**
Was trying to downgrade iPhone 5s 12.5.1
Each and every time failed on "Sending iBSS/iBEC"
Tried both Catalina fixes

**Screenshots**
`sudo python3 ./vieux -i iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw `
![image](https://user-images.githubusercontent.com/38182908/108261864-dd693b80-716c-11eb-82f8-14d98d9021f7.png)

**Computer (please complete the following information):**
![image](https://user-images.githubusercontent.com/38182908/108262026-0ee20700-716d-11eb-8602-a897683eb211.png)
 - Python Version: 3.7.3
 - Vieux Version: 1.0.1

**iOS Device (please complete the following information):**
 - Device: iPhone6,1 (iPhone 5s 32gb 12.5.1 (Find my iPhone: off, security pin: off))
 - Desired Version: iOS 10.3.3
 -

**Comment by j188482367** [comment]
same

**Comment by igoriokas** [comment]
I have solved this issue for my system.
In my case the ./resources/bin/irecovery wasn't working even after all the fixes in the describtion.
I had to recompile the irecovery utility from [sources](https://github.com/Chronic-Dev/libirecovery) and then it worked 😀
also did the same for the tsschecker which also seemed not to work.
You can try with my binaries [irecovery.zip](https://github.com/MatthewPierson/Vieux/files/6018294/irecovery.zip)
