### ISSUE TITLE
May I ask if its possible to downgrade to 8.4.1 for iPad mini 2?

### ISSUE THREAD

**Issue by RoadToDream** [MatthewPierson/Vieux#234]
**Describe the issue**
May I ask if its possible to downgrade to 8.4.1 for iPad mini 2?
**Screenshots**
REQUIRED - 
Add screenshots of ALL the terminal output, including the command.

**Computer (please complete the following information):**
REQUIRED -
 - Computer Model [e.g. MacBook Pro 2016 or macbookpro14,3 + Year]  
 - MacOS Version [e.g. 10.14.3]
 - Python Version [e.g. Python3.7]
 - Vieux Version [e.g. Public Beta: 2 or Commit "ec3d67b944b626519e5ecdd682e4d3cf89dc7e51"]

**iOS Device (please complete the following information):**
REQUIRED -
 - Device: [e.g. iPhone6,2]
 - Desired Version: [e.g. iOS 10.3.3]

**Additional context**
Add any other context about the issue here.

**Comment by MatthewPierson** [comment]
No it isn't. All the supported devices + iOS versions are listed in the README.

**Comment by RoadToDream** [comment]
> No it isn't. All the supported devices + iOS versions are listed in the README.

Thank you for bringing this toolset! 

Just a little sad I cannot go back to 8. :(
