### ISSUE TITLE
iPhone 6,1 iOS 12.4.7 > 10.3.3, usb.core.usberror [Errno None] Other error

### ISSUE THREAD

**Issue by Anifiedd** [MatthewPierson/Vieux#242]
**Describe the issue**
REQUIRED - 
A clear and concise description of what the issue is and what you have already tried to fix the issue.

I'm trying to downgrade my iPhone 5s (6,1) from iOS 12.4.7 to iOS 10.3.3. I have the correct IPSW from ipsw.me, the phone was in DFU mode the whole time, I have Xcode, installed everything from requirements.txt, python 3, and the phone I'm trying to downgrade has been jailbroken on iOS 12. I do use the Mojave patcher by dosdude1 so that might have to do with something? I'll include my about this Mac in the screenshots section and my about this iPhone. 
**Screenshots**
REQUIRED - 
![Screen Shot 2021-05-01 at 10 27 08 AM](https://user-images.githubusercontent.com/83507077/116787223-a5358180-aa68-11eb-8533-48b1e4fabc17.png)
![Screen Shot 2021-05-01 at 10 27 20 AM](https://user-images.githubusercontent.com/83507077/116787235-b1b9da00-aa68-11eb-9bcf-b8c8d04291ba.png)
![Screen Shot 2021-05-01 at 10 19 04 AM](https://user-images.githubusercontent.com/83507077/116787247-b7172480-aa68-11eb-85c0-d301ca918757.png)
![IMG_0028](https://user-images.githubusercontent.com/83507077/116787259-bc746f00-aa68-11eb-879b-74b2c8a686c7.jpg)

**Computer (please complete the following information):**
REQUIRED -
 - Computer Model 13" White MacBook Late-2009 
 - MacOS Version 10.14.6
 - Python Version 3.9
 - Vieux Version commit b3c5f5f7a797692ece4d03a1df89daa596ffcd95

**iOS Device (please complete the following information):**
REQUIRED -
 - Device: iPhone 6,1
 - Desired Version: 10.3.3

**Additional context**
Add any other context about the issue here.

**Comment by Grandboy46** [comment]
I heard that ipwndfu is broken on Dosdude’s Mojave patcher. You would need a newer mac to enter pwndfu.

**Comment by rileyclos** [comment]
> I heard that ipwndfu is broken on Dosdude’s Mojave patcher.

Ahh ok. I'll try to do this on High Sierra and see if it works, thank you!
