### ISSUE TITLE
iPad Air can not be recognized

### ISSUE THREAD

**Issue by monstarvincent** [MatthewPierson/Vieux#25]
Hello! Matty! I'm running on MacBook Pro Mojave 10.14.6. Why can't I connect the iPad Air that I have entered DFU mode.

Vincents-MacBook-Pro:Vieux-master root# python3 vieux -i /Users/vincent/Downloads/ipad.ipsw 
Given IPSW Path is /Users/vincent/Downloads/ipad.ipsw
Vieux - A tool for 32/64 Bit OTA downgrades
Still in BETA so expect issues/broken things
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in normal mode
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
No device found in DFU mode, assuming device to be 32 Bit...
No valid 32 Bit information found. Exiting...
Vincents-MacBook-Pro:Vieux-master root#

**Comment by monstarvincent** [comment]
I have already installed all the requirements.

**Comment by MatthewPierson** [comment]
Is the iPad in DFU mode or recovery mode? DFU mode means the screen will be black with nothing on it where recovery mode has the iTunes logo.

**Comment by MatthewPierson** [comment]
I will be closing this issue in 24 hours if you no longer need help/the issue has been resolved. If you still need help then comment with what you need and I will not close it.
