### ISSUE TITLE
inyhrs-iMac:Vieux-master inyhr$ ./vieux -i /Users/inyhr/Desktop/Vieux-master/iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw  Traceback (most recent call last):   File "./vieux", line 6, in <module>     import ipsw   File "/Users/inyhr/Desktop/Vieux-master/ipsw.py", line 3, in <module>     import bsdiff4 ModuleNotFoundError: No module named 'bsdiff4'

### ISSUE THREAD

**Issue by nb713** [MatthewPierson/Vieux#29]
I just wanna downgrade my phone and I can't get past this help

**Comment by MatthewPierson** [comment]
Read the readme. You need to install the dependencies before starting.

**Comment by zhangweiii** [comment]
maybe you should use virtual environment like [poetry](https://github.com/python-poetry/poetry) or [pyenv](https://github.com/pyenv/pyenv) or others, i face same error,then i use virtual environment,it worked

**Comment by MatthewPierson** [comment]
You shouldn't need to use a virtual environment, just run "pip3 install -r requirements.txt" and then that should fix the issues. Also make sure you update to the latest files

**Comment by MatthewPierson** [comment]
I will be closing this issue in 24 hours if you no longer need help/the issue has been resolved. If you still need help then comment with what you need and I will not close it.
