### ISSUE TITLE
Please enter the root password to your device (Default is 'alpine')

### ISSUE THREAD

**Issue by czqn8** [MatthewPierson/Vieux#3]
Connecting to device via SSH...
ERROR: SSH/SCP failed, (need to add more details in this part)
Exiting...

**Comment by MatthewPierson** [comment]
Do you have OpenSSH installed? You can test by just connecting to it with terminal via “ssh root@ipaddress”.

**Comment by bodenchristian** [comment]
I also get this error on my iPhone 5 (10.3.4) It was hacktivated so maybe that's the problem? SSH does work on the computer though as I used it to hacktivate the phone.

**Comment by mokhtarDZ27** [comment]
[Connecting to device via SSH...
ERROR: SSH/SCP failed, (need to add more details in this part)
Exiting...] , is this mean that i must have a jailbroken device ?

**Comment by mokhtarDZ27** [comment]
[Connecting to device via SSH...
ERROR: SSH/SCP failed, (need to add more details in this part)
Exiting...] ,  does this mean that i must have a jailbroken device ?

**Comment by czqn8** [comment]
@mokhtarDZ27 Jailbreak install openSSH

**Comment by mokhtarDZ27** [comment]
so it will not work without jailbreak ??

**Comment by mokhtarDZ27** [comment]
> @mokhtarDZ27 Jailbreak install openSSH

so it will not work without jailbreak

**Comment by mokhtarDZ27** [comment]
@czqn8  so it will not work without jailbreak ?

**Comment by MatthewPierson** [comment]
@czqn8 I will be closing this issue in 24 hours if you no longer need help/the issue has been resolved. If you still need help then comment with what you need and I will not close it.

**Comment by mokhtarDZ27** [comment]
Please could you answer my question : ( so it will not work without jailbreak ?  )

**Comment by czqn8** [comment]
testing
