### ISSUE TITLE
Unable to get SEPNonce from lockdownd 

### ISSUE THREAD

**Issue by dihbao197** [MatthewPierson/Vieux#30]
Apparently I did all the steps but it gives this error and I don't know whether it affects or not. Because I cannot downgarde as if it will give me this error 
ERROR: SSH/SCP failed, (need to add more details in this part)

So do I have to jailbreak my phone or something?

**Comment by MatthewPierson** [comment]
Yes your 32 bit device needs to be jailbroken with OpenSSH installed for this to work.

**Comment by dihbao197** [comment]
Okay thanks I will do it now.

**Comment by MatthewPierson** [comment]
Also "Unable to get SEPNonce from lockdownd" is something that will always print when using a 32 Bit device, just ignore it. It doesn't matter and won't effect anything

**Comment by dihbao197** [comment]
um.. I still get this error even though I already installed OpenSSH 
ERROR: SSH/SCP failed, (need to add more details in this part)

**Comment by MatthewPierson** [comment]
If you are on iOS 10 you need to reboot and rejailbreak after installing OpenSSH, its a bug with the 10.x 32 Bit jailbreak annoyingly.

**Comment by dihbao197** [comment]
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/client.py:837: UserWarning: Unknown ssh-rsa host key for 192.168.31.65: b'f9d1910cb01ec3232b73b248060aa200'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
ERROR: SSH/SCP failed, (need to add more details in this part)
Exiting...
  
(The next error I got after following your steps.)

**Comment by MatthewPierson** [comment]
Easiest way to fix this is to run "rm -rf ~/.ssh/known_hosts" and try again. This will remove any saved ssh keys but if you don't know what that is/means or have a use for them then its fine to delete the file, or just back it up with a different name, run Vieux, then move the known_hosts file back

**Comment by MatthewPierson** [comment]
I will be closing this issue in 24 hours if you no longer need help/the issue has been resolved. If you still need help then comment with what you need and I will not close it.
