### ISSUE TITLE
Corret ipse PATH???

### ISSUE THREAD

**Issue by toromano** [MatthewPierson/Vieux#36]
/Users/lolk/Desktop/iPad_64bit_10.3.3_14G60_Restore.ipsw is not a zip archive! Are you sure you inserted the correct ipsw path?

hi sir. sorry for this topic. why it said that? 

i did the old way:

cd vieux
./vieux -i "PATH/TO/.ipsw"

and said  PATH/TO/.ipsw is not a zip archive! Are you sure you inserted the correct ipsw path?

really I m a noob .... how can I use new method ? I don't understand new usage... PLS help me

**Comment by toromano** [comment]
i solved. :)

**Comment by cdlenfert** [comment]
What did you do to resolve this error? I get the same

**Comment by cdlenfert** [comment]
I figured it on on my end too. I have an iPad 2,4 (2012 16gb model) and the .ipsw file name contains a coma. This creates a backslash character in the file path. That is the problem. If you rename the ipsw to something like "ipad2restore.ipsw" or anything without spaces or comas you should be good to go.
