### ISSUE TITLE
N41 iPhone 5 missing from ipsw.py

### ISSUE THREAD

**Issue by NotHereForTheDong** [MatthewPierson/Vieux#4]
iPhone 5,1 has an iBSS of iBSS.n41 in some models. The IPSW.py script doesn’t seem to include this. Only iBSS.n42

When I edited the py file it ran fine after

**Comment by MatthewPierson** [comment]
Will fix this soon, thank for telling me! I had made the assumption that both models of the 5 shared the same iBSS/iBEC like the 5s does but looks like that’s incorrect

**Comment by MatthewPierson** [comment]
Just pushed an update which should have fixed this. Thank you for letting me know it was broken!

**Comment by NotHereForTheDong** [comment]
Thanks Matty! Your great
