### ISSUE TITLE
[Problem]Is it possible to support iPhone6s (Soc-S8000) in the future?

### ISSUE THREAD

**Issue by xxzj990** [MatthewPierson/Vieux#46]
iPhone6s
[S8000](https://www.theiphonewiki.com/wiki/S8000)

**Comment by MatthewPierson** [comment]
[Please read this.](https://github.com/MatthewPierson/Vieux#what-devices-does-this-supportwhen-will-it-support-my-ipad-xx-or-iphone-xx)
