### ISSUE TITLE
Is there any other way to run it on lower edition?

### ISSUE THREAD

**Issue by LJ-Mac** [MatthewPierson/Vieux#49]
how to make it work on 10.13.6?

**Comment by LJ-Mac** [comment]
The phone always jump out of DFU mode in 10.13.6.

**Comment by XDUser** [comment]
Just a thought, if the reason you're using 10.13.6 is because your Mac doesn't support Mojave or newer, you can try to use DosDude1's MacOS Mojave or Catalina Patcher.

**Comment by MatthewPierson** [comment]
There is no, and will be no, support for versions lower then 10.14.x. I don't have time to spend on getting it to work on a two year old OS version that most people don't use anymore.
