### ISSUE TITLE
Return code 241

### ISSUE THREAD

**Issue by Bigbadare** [MatthewPierson/Vieux#5]
Hello Matthew,
Thank you first for all this work done.
I used until your update your old method, it worked on the ipad air that I manage for my work (only 10.3.3 in our school, I do not wonder why .... that's how it is, the chef said .....).

I tested "vieux", at home, several times, on my imac in 10.14.6 and I get this screen each time when the script is launched, or the ipad will come out of dfu mode and to boot normally after unzipping.

Two iPad Air A1474 tested on my imac, same results, once this error or once the ipad boot normally and the command stop.

A screenshot when return code 241

ps: sorry for my bad english, i'm french, but suddenly i love the name you chose for this tool
![vieux-log](https://user-images.githubusercontent.com/58863623/70830063-9e648b00-1def-11ea-90f2-a050ff5fbaf4.jpg)

**Comment by MatthewPierson** [comment]
Please try the latest version that I just pushed and if it still errors, send me the full log again but also include the 'errorrestorelog.txt' file (or the text inside it) so I can properly debug this, thank you! Also don't worry about your English its perfectly fine!

**Comment by Bigbadare** [comment]
Dear Matthew, I did what you advised me to do.
Here are the results :
-the script stops with the error as on the attached files
-Or my ipad restarts normally after the line "Found, CPID .... blablabla".

My imac is up to date (mojave of course), I did it just before trying old (update brew, python, cleaning the system), and I take a new Apple certified lightning cable to launch the script.

I am sure you will have a solution.

I thank you in advance.

[errorlogrestore.txt](https://github.com/MatthewPierson/Vieux/files/3963531/errorlogrestore.txt)
![vieux-log](https://user-images.githubusercontent.com/58863623/70844661-c3cfb400-1e44-11ea-8041-5379a3259e0f.jpg)

**Comment by toromano** [comment]
> Dear Matthew, I did what you advised me to do.
> Here are the results :
> -the script stops with the error as on the attached files
> -Or my ipad restarts normally after the line "Found, CPID .... blablabla".
> 
> My imac is up to date (mojave of course), I did it just before trying old (update brew, python, cleaning the system), and I take a new Apple certified lightning cable to launch the script.
> 
> I am sure you will have a solution.
> 
> I thank you in advance.
> 
> [errorlogrestore.txt](https://github.com/MatthewPierson/Vieux/files/3963531/errorlogrestore.txt)
> ![vieux-log](https://user-images.githubusercontent.com/58863623/70844661-c3cfb400-1e44-11ea-8041-5379a3259e0f.jpg)

did you fixed?

**Comment by MatthewPierson** [comment]
Please try with the latest commit, it has a potential fix for this issue but I can't test myself as I don't have any A7 iPads (This is the same message I'm replying to all relevant issues :) ) @Bigbadare

**Comment by MatthewPierson** [comment]
@Bigbadare @toromano Latest commit has fully fixed all iPad Air and iPad Mini 2 issues! Please give it a try and sorry for taking so long, took me forever to figure out the issue and actually fix it!
