### ISSUE TITLE
Unable to put device into restore mode (Error=-10)

### ISSUE THREAD

**Issue by foivos-laz** [MatthewPierson/Vieux#51]
My iPad Air (iPad4,2) after flashing Green for a second and almost started restoring gave me a -10 error and wiped my iPad as a result i had to reinstall iOS 12.4.3...
![Screenshot 2019-12-30 at 17 50 42](https://user-images.githubusercontent.com/59368838/71589902-46d45800-2b2f-11ea-9659-f3acb46abc42.png)

**Comment by MatthewPierson** [comment]
Try using the tool again, might just be a one off issue that won't happen on the next restore, and let me know what happens!

**Comment by foivos-laz** [comment]
It actually worked after re doing it! Thank you a lot for the tool though, I managed to downgrade my iPhone 4S to iOS 8.4.1 and my iPad Air to iOS 10.3.3!

**Comment by MatthewPierson** [comment]
Good to hear! Sorry for the late response, been busy with family and traveling back home.
