### ISSUE TITLE
Blue screen on device restart

### ISSUE THREAD

**Issue by Georgecox7** [MatthewPierson/Vieux#54]
So I’ve successfully done the restore from iOS 12.4.3 back to 10.3.3 but now every time I restart my device the screen goes blue for around a second - not too sure if this is an issue or meant to happen - wanted to let you know in case you need to make any changes - thanks for the tool tho - really useful

**Comment by MatthewPierson** [comment]
I've never ran into that issue myself, only ever had a blue screen when the restore failed. If it doesn't cause any other issues then I wouldn't worry about it, it's probably harmless!

**Comment by Georgecox7** [comment]
Hey Matty, thanks for the quick reply, if anyone else asks about this then I managed to fix the issue by downloading ‘succession’ on Cydia and reinstalling iOS 10.3.3 from there

Thanks
