### ISSUE TITLE
5s drops out of DFU mode after being identified. Vieux times out...

### ISSUE THREAD

**Issue by tlark740** [MatthewPierson/Vieux#62]
**Describe the issue**
5s 6,1 in DFU mode. vieux identifies the phone as:

Found: CPID:8960 CPRV:11 CPFM:03 SCEP:01 BDID:00 ECID:0000070D895F2CB0 IBFL:1C SRTG:[iBoot-1704.10]

after about 15 secs....device exits DFU mode, even though the screen stays dark.

ERROR: No Apple device in DFU Mode 0x1227 detected after 30.00 second timeout. Exiting.
Place the device into DFU mode again and re-run Vieux

Consistent behavior after many tries. Tried with iTunes/helper running and not running. No difference.

**Screenshots**

**Computer (please complete the following information):**
REQUIRED -
 - Hackintosh. VMware 15.1 Workstation
![Screen Shot 2020-01-08 at 8 37 42 PM](https://user-images.githubusercontent.com/59680879/72043929-5a866980-3267-11ea-943d-2289cdd271f4.png)
 player
 - MacOS Version.  10.14.6 Mojave
 - Python Version     Python3.7
 - Vieux Version    1.0

**iOS Device (please complete the following information):**
REQUIRED -
 - Device: iPhone6,1
 - Desired Version: iOS 10.3.3
 - Currently loaded at 12.4.4

**Additional context**
Add any other context about the issue here.

**Comment by MatthewPierson** [comment]
Checkm8 doesn't work in a VM sorry, you'd need to make a Hackintosh to use this if you don't have an actual Mac.

**Comment by a1266143** [comment]
same issue,hackintosh version:10.14.3

**Comment by tlark740** [comment]
Thanks for the reply. Would be helpful to add the fact that VM's don't work in the README to keep others from pursuing this path.
