### ISSUE TITLE
Unable to receive message from FDR 0x7fec32596ac0 (-2). 0/2 bytes

### ISSUE THREAD

**Issue by 7HE-W0R1D** [MatthewPierson/Vieux#64]
**Describe the issue**
REQUIRED - 
Everything goes fine and my phone's screen has the apple logo and progress bar on, but the bar won't go and then the screen turns blue&green and something then goes black, in the terminal, it gives out the error "Unable to receive message from FDR 0x7fec32596ac0 (-2). 0/2 bytes"
Tried about 5 times and the result didn't change.

**Screenshots**
REQUIRED - 
Add screenshots of ALL the terminal output, including the command.
<img width="577" alt="Screen Shot 2020-01-10 at 10 20 08" src="https://user-images.githubusercontent.com/42311695/72120401-d6310500-3392-11ea-9182-05742650fc47.png">
<img width="574" alt="Screen Shot 2020-01-10 at 10 19 33" src="https://user-images.githubusercontent.com/42311695/72120411-d92bf580-3392-11ea-83fa-8199a9949374.png">

**Computer (please complete the following information):**
REQUIRED -
 - Computer Model MacBook Pro (Retina, 13-inch, Late 2013)  
 - MacOS Version 10.14.6 (18G103)
 - Python Version python 2.7 & python3.7
 - Vieux Version 1.0

**iOS Device (please complete the following information):**
REQUIRED -
 - Device: iPhone6,2
 - Desired Version: iOS 10.3.3

**Additional context**
Add any other context about the issue here.
I grabbed 2 logs but basically they are the same in error.
[errorlogrestore01.txt](https://github.com/MatthewPierson/Vieux/files/4043636/errorlogrestore01.txt)

**Comment by 7HE-W0R1D** [comment]
btw even if there is no "patches error" the problem still persists.

**Comment by MatthewPierson** [comment]
Did you upload the right error log? The one you uploaded seems to end before anything on the device actually happens.

**Comment by 7HE-W0R1D** [comment]
I think its the right one, still trying now. If the error persists I will upload a new log :)

**Comment by 7HE-W0R1D** [comment]
OMG tried on my other iPhone 5s(also an iPhone 6,2) and the script worked!!!
I can tell the difference is that the previous phone has a broken system or something, it always boots into recovery instead of the iOS.
However, both phones cannot boot to system since yesterday when I'm trying the method on reddit. Confused by that.
Anyway, thanks again for your great work!

**Comment by MatthewPierson** [comment]
With the broken phone, try doing a clean DFU restore to 12.4.4 in iTunes, then try downgrading it with my tool. When you say they both cannot boot to system, are they just booting to recovery mode or bootlooping?

**Comment by 7HE-W0R1D** [comment]
They boot into recovery, not bootloop

**Comment by 7HE-W0R1D** [comment]
Will try clean DFU restore soon downloading the ipsw :)

**Comment by 7HE-W0R1D** [comment]
When I restore iTunes give me error 9, always :(

**Comment by xiaji-cn** [comment]
DFU restore to 12.4.4 in iTunes, and done。I succeed
