### ISSUE TITLE
Error with pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by HoangThienBinh** [MatthewPierson/Vieux#67]
When i use this command: pip3 install -r requirements.txt

I was stucked in this step, please help me

Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/__pycache__/six.cpython-37.pyc'
Consider using the `--user` option or check the permissions.

You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
hoangngo@HoangNgos-MacBook-Pro Vieux-master %

**Comment by xiajibashe** [comment]
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt --user
