### ISSUE TITLE
iPad Air Return code: 249 

### ISSUE THREAD

**Issue by insomnium098** [MatthewPierson/Vieux#76]
I get the Return code 249 whenever i try to restore, i've also tried running vieux using both python2 and python3 and using sudo.
**Screenshots**
<img width="1231" alt="Captura de Pantalla 2020-01-26 a la(s) 12 13 30 p  m" src="https://user-images.githubusercontent.com/22182597/73139612-4d25f900-4035-11ea-9b7f-ef854c9df011.png">

<img width="1143" alt="Captura de Pantalla 2020-01-26 a la(s) 12 17 24 p  m" src="https://user-images.githubusercontent.com/22182597/73139664-e6eda600-4035-11ea-9fa1-e1de83a1aee6.png">

**Computer**
REQUIRED -
 - Computer Model: MacBook Pro 15 2017 
 - MacOS Version : 10.14.6
 - Python Version: Python 3.7.4
 - Vieux Version: Commit "01a85be633debd870f993611984e9b8ceec19796"

**iOS Device (please complete the following information):**
 - Device: iPad 4,1
 - Desired Version: iOS 10.3.3
[errorlogshsh.txt](https://github.com/MatthewPierson/Vieux/files/4114012/errorlogshsh.txt)

**Comment by insomnium098** [comment]
**FIX**
@MatthewPierson I've fixed the bug by modifying the _device.py_ script, in line 98, i added 60 seconds to sleep

**Comment by MatthewPierson** [comment]
I will edit device.py and make the sleep time slightly longer, 60 seconds is overkill though
