### ISSUE TITLE
iPad 3,3 Error

### ISSUE THREAD

**Issue by yarkovalexey** [MatthewPierson/Vieux#79]
**Screenshots**
iMac-Alexey:Vieux alexey$ python3 vieux -i iPad3,3_8.4.1_12H321_Restore.ipsw

Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
iPad3,3_8.4.1_12H321_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
ERROR: normal_idevice_new: can't open device with UDID 39dd351fb8a61d81be46f0967222506cf3cebecf
Unable to get SEPNonce from lockdownd
NOTE: Unable to get SepNonce from device
Starting iBSS/iBEC patching
Traceback (most recent call last):
  File "vieux", line 89, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/alexey/Desktop/Vieux/ipsw.py", line 146, in unzipIPSW
    createCustomIPSW32(fname)
  File "/Users/alexey/Desktop/Vieux/ipsw.py", line 298, in createCustomIPSW32
    bsdiff4.file_patch_inplace("iBSS.j3.RELEASE.dfu", pad33ibss)
  File "/usr/local/lib/python3.7/site-packages/bsdiff4/format.py", line 101, in file_patch_inplace
    with open(path, 'r+b') as fo:
FileNotFoundError: [Errno 2] No such file or directory: 'iBSS.j3.RELEASE.dfu'

**Computer (please complete the following information):**
REQUIRED -
 - Computer Model iMac 19,2
 - MacOS Version 10.14.6
 - Python Version Python3.7
 - Vieux Version 1.0.1

**iOS Device (please complete the following information):**
REQUIRED -
 - Device: iPad 3,3 (iOS 9.3.6)
 - Desired Version: iOS 8.4.1

**Additional context**
Please help me deal with the error.

**Comment by MatthewPierson** [comment]
I have just pushed an update to fix this issue, please update and try again! Let me know if it works

**Comment by yarkovalexey** [comment]
**I'm sorry, but downgrade is not possible because**

iMac-Alexey:Vieux alexey$ python3 vieux -i /Users/alexey/Desktop/Vieux/iPad3\,3_8.4.1_12H321_Restore.ipsw 

Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
/Users/alexey/Desktop/Vieux/iPad3,3_8.4.1_12H321_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
ERROR: normal_idevice_new: can't open device with UDID 00008030-00166D6E3E50802E
Unable to get SEPNonce from lockdownd
NOTE: Unable to get SepNonce from device
Starting iBSS/iBEC patching
Traceback (most recent call last):
  File "vieux", line 89, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/alexey/Desktop/Vieux/ipsw.py", line 146, in unzipIPSW
    createCustomIPSW32(fname)
  File "/Users/alexey/Desktop/Vieux/ipsw.py", line 299, in createCustomIPSW32
    shutil.copy("iBSS.j2a.RELEASE.dfu ", "ibss")
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'iBSS.j2a.RELEASE.dfu '

**Comment by MatthewPierson** [comment]
Pushed another update, accidentally made a typo which caused this error. Download the latest update and try again!

**Comment by yarkovalexey** [comment]
**I ran the program twice and got an error.**

Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
/Users/alexey/Desktop/Vieux/iPad3,3_8.4.1_12H321_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
ERROR: normal_idevice_new: can't open device with UDID 00008030-00166D6E3E50802E
Unable to get SEPNonce from lockdownd
NOTE: Unable to get SepNonce from device
Starting iBSS/iBEC patching
Looks like you are downgrading an iPad3 to 8.4.1!
Please enter your devices IP address (Find it in WiFi settings):
192.168.0.9
Please enter the root password to your device (Default is 'alpine'):

Connecting to device via SSH...
Device is not running iOS 10.x, using normal TFP0 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
ERROR: No Apple device in DFU Mode 0x1227 detected after 30.00 second timeout. Exiting.
Place the device into DFU mode again and re-run Vieux

**Then I execute the program instruction and get the following.**

Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
/Users/alexey/Desktop/Vieux/iPad3,3_8.4.1_12H321_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Starting iBSS/iBEC patching
Looks like you are downgrading an iPad3 to 8.4.1!
Please enter your devices IP address (Find it in WiFi settings):
192.168.0.9
Please enter the root password to your device (Default is 'alpine'):

Connecting to device via SSH...
ERROR: SSH/SCP failed, make sure that you are jailbroken with OpenSSH installed, try rebooting the device
Exiting...

**Comment by MatthewPierson** [comment]
On the first run did you press the home button and unplug then replug it in?

**Comment by yarkovalexey** [comment]
This is great advice!
I did not notice the inscription.


> Please press the home button on your device or unplug and replug it back in.


Thanks for the help! 
I successfully downgraded iPad 3,3 on iOS 8.4.1.

P.S.: In the future I will check the downgrade of iOS to iPad 2,2.

**Comment by yarkovalexey** [comment]
Vieux - A tool for 32/64 Bit OTA downgrades

Current version is: 1.0.1
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
iPad2,2_8.4.1_12H321_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
ERROR: normal_idevice_new: can't open device with UDID
Unable to get SEPNonce from lockdownd
NOTE: Unable to get SepNonce from device
Starting iBSS/iBEC patching
Looks like you are downgrading an iPad2 to 8.4.1!
Please enter your devices IP address (Find it in WiFi settings):
192.168.0.107
Please enter the root password to your device (Default is 'alpine'):

Connecting to device via SSH...
Device is not running iOS 10.x, using normal TFP0 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
Restoring...
Note that errors about 'BbSkeyId', 'FDR Client', 'BasebandFirmware Node' and 'ERROR: zip_name_locate: Firmware/all_flash/manifest' are not important.
Just ignore them and only report errors that actually stop the restore.
ERROR: Unable to connect to FDR client (-2)
ERROR: Failed to start FDR Ctrl channel
Files cleaned.
Finished! Enjoy your downgraded device :)

**Thanks, I also successfully downgrade iPad 2.2 on iOS 8.4.1.**
