### ISSUE TITLE
Python Error while rebuilding IPSW

### ISSUE THREAD

**Issue by polishmathu** [MatthewPierson/Vieux#8]
I'm on macOS Mojave 10.14.6 (rMBP 15" 2015) and I'm trying to downgrade my iPhone 5s. 

This is the error I get: 
`Starting iBSS/iBEC patching
Patched iBSS/iBEC
About to re-build IPSW
Traceback (most recent call last):
  File "./vieux", line 48, in <module>
    ipsw.unzipIPSW(path)
  File "/Users/mateusz/.Trash/Vieux/ipsw.py", line 111, in unzipIPSW
    createCustomIPSW64(fname, devicemodel)
  File "/Users/mateusz/.Trash/Vieux/ipsw.py", line 208, in createCustomIPSW64
    if device == "iPhone5s":
UnboundLocalError: local variable 'device' referenced before assignment`

Here is a screenshot for more readability:
<img width="567" alt="Screenshot 2019-12-13 at 22 52 37" src="https://user-images.githubusercontent.com/47923073/70834704-4cc1fd80-1dfb-11ea-9b6c-4617ae311b91.png">

I've tried multiple times and I've even tried moving the IPSW to a different directory.
The python requirements are installed.

**Comment by MatthewPierson** [comment]
Are you using the latest version? It also looks like you are running the tool from the .trash folder which might be causing issues. Try downloading the latest version and try again

**Comment by polishmathu** [comment]
Downloaded the latest version (git cloned it just to be sure) into a different directory, emptied the trash folder and it still doesn't work, but this time I got more errors: 

<img width="897" alt="Screenshot 2019-12-13 at 23 30 40" src="https://user-images.githubusercontent.com/47923073/70836592-ea6bfb80-1e00-11ea-87be-41af10097521.png">


When I tried running it again I didn't get those "new" errors.

**Comment by polishmathu** [comment]
I tried once again with the newer version (the one where you modified ipsw.py file about 20 minutes ago) and now I get this error all the time: 

<img width="838" alt="Screenshot 2019-12-14 at 14 44 48" src="https://user-images.githubusercontent.com/47923073/70849564-60637780-1e80-11ea-83ea-c084e8fbe532.png">

**Comment by MatthewPierson** [comment]
Sorry made a typo in that update, try again with latest version now.

**Comment by polishmathu** [comment]
I thought it would work now, I even got the green screen on the phone, then it showed me an Apple logo with the loading bar (which doesn't load) and after a minute or two I got a new error: 

<img width="745" alt="Screenshot 2019-12-14 at 15 18 50" src="https://user-images.githubusercontent.com/47923073/70849943-5ee87e00-1e85-11ea-82c1-5968eee4ff95.png">

It's been stuck on this for about 15 minutes.

Also, does it matter whether iTunes is opened or closed?

**Comment by MatthewPierson** [comment]
Shouldn’t matter if iTunes is open. Can’t really help unless it actually errors out, not just stalls/freezes.

**Comment by polishmathu** [comment]
I had waited for about 30 more minutes before I disconnected the phone, nothing else showed up. 

I think I got the same error while using the 10.3.3 OTA downgrader script. 

Maybe there is something wrong with my macOS install or phone, I don't know and I don't own any other Macs to try.

So for now I think I have to give up. Thank you for everything!

**Comment by MatthewPierson** [comment]
@polishmathu I will be closing this issue in 24 hours if you no longer need help/the issue has been resolved. If you still need help then comment with what you need and I will not close it.
