### ISSUE TITLE
iPad mini2(A1489) auto reboot in DFU mode and nothing happened

### ISSUE THREAD

**Issue by idis573** [MatthewPierson/Vieux#86]
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
iPad_64bit_10.3.3_14G60_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Found: CPID:8960 CPRV:11 CPFM:03 SCEP:01 BDID:0A ECID:000007F4F1560230 IBFL:1C SRTG:[iBoot-1704.10]
ERROR: No Apple device in DFU Mode 0x1227 detected after 30.00 second timeout. Exiting.
Place the device into DFU mode again and re-run Vieux

**Comment by idis573** [comment]
mac os is 10.14.6  version

**Comment by lryong** [comment]
> mac os is 10.14.6 version

I encounter the same problem, how to slove it,  my mac os is 10.15.2

**Comment by whypro** [comment]
`brew install libusb` may solve this problem.
