### ISSUE TITLE
ModuleNotFoundError: No module named 'bsdiff4'

### ISSUE THREAD

**Issue by czqn8** [MatthewPierson/Vieux#95]
Traceback (most recent call last):
  File "./vieux", line 6, in <module>
    import ipsw
  File "/Users/Alan/Vieux/ipsw.py", line 3, in <module>
    import bsdiff4
ModuleNotFoundError: No module named 'bsdiff4'

**Comment by uoftliuyihe** [comment]
I also met this error, could any one please help us if he/she knows how to solve this problem?

**Comment by uoftliuyihe** [comment]
This happens to the last step after input the "./vieus -I " code  and drag the ipsw file. For the first few cods it runs  correctly  without any error appears.

**Comment by RepairsInMotion** [comment]
pip3 install -r requirements.txt

**Comment by alxudm** [comment]
I can't solve this problem. Can anyone help? I did this command "pip3 install -r requirements.txt" but terminal ask form more options.

**Comment by RepairsInMotion** [comment]
You must install python.
I'm using High Sierra so I installed Python 2.7. Then cd into Vieux and run pip3 install -r requirements.txt without the quotation marks.
If it still doesn't work then log the error so we can assist you better.

**Comment by Merculous** [comment]
This is just caused by not installing the required modules used. Make sure you install the modules like so: (macos) pip3 install -r requirements / (linux) pip3 install --user -r requirements.txt

**Comment by uoftliuyihe** [comment]
**I find the same problem happens again, even after i followed the instruction. The output result is attached down below, please take a look.**

"Last login: Wed Feb 26 15:54:50 on ttys000
(base) MacBook-Pro:~ lewis$ cd /Users/lewislights/Desktop/Vieux-master-2 
(base) MacBook-Pro:Vieux-master-2 lewis$ pip3 install -r requirements.txt
Requirement already satisfied: bcrypt==3.1.7 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (3.1.7)
Requirement already satisfied: bsdiff4==1.1.9 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.1.9)
Requirement already satisfied: cffi==1.13.2 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.13.2)
Requirement already satisfied: cryptography==2.8 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.8)
Requirement already satisfied: paramiko==2.7.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.7.0)
Requirement already satisfied: pycparser==2.19 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2.19)
Requirement already satisfied: PyNaCl==1.3.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: pyusb==1.0.2 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.0.2)
Requirement already satisfied: scp==0.13.2 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (0.13.2)
Requirement already satisfied: six==1.13.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.13.0)
(base) MacBook-Pro:Vieux-master-2 lewis$ ./vieux -i /Users/lewis/Desktop/Vieux-master-2/iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw 
Traceback (most recent call last):
  File "./vieux", line 6, in <module>
    import ipsw
  File "/Users/lewis/Desktop/Vieux-master-2/ipsw.py", line 3, in <module>
    import bsdiff4
ModuleNotFoundError: No module named 'bsdiff4'
(base) MacBook-Pro:Vieux-master-2 lewis$"

**Comment by Merculous** [comment]
Does 'pip3 install bsdiff4"install the module or is it not downloaded? I'm not sure why its giving that error even if this exists.

> Requirement already satisfied: bsdiff4==1.1.9 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.1.9)

**Comment by nicho1asdev** [comment]
I also encountered this problem, but I managed to fix it. You need to install each module in "requirements.txt" with the command _python3 -m pip install moduleName_. Example _python3 -m pip install bsdiff4_

**Comment by teddybearrohan** [comment]
I tried running pip3 install -r requirements.txt

It said "could not install packages due to EnvironmentError: permission denied"

The same thing happens if I run python3 -m pip install bsdiff4
